### ISSUE TITLE
Test uses non-function type aliases and @dart=2.6 in the same file.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/co19#1019]
The test `LanguageFeatures/nnbd/weak/type-aliases/legacy_libraries_A01_t04.dart` contains the following code:
```dart
// @dart=2.6
// SharedOptions=--enable-experiment=nonfunction-type-aliases
// Requirements=nnbd-weak
import "../../../../Utils/expect.dart";
import "../opted_in_lib.dart";

typedef AAlias = A;
typedef StringAlias = String;
typedef IntAlias = int;
```
Those aliases are invalid because experiments cannot be enabled for libraries at language version 2.6, only for libraries which are already on the newest version.

**Comment by scheglov** [comment]
The same is in `LanguageFeatures/nnbd/weak/type-aliases/legacy_library_aliases_lib.dart`, affecting multiple tests.

```dart
// @dart=2.6
library legacy_library_aliases_lib;

class A {
  void bar() {}
  int operator[](int index) => index;
}

typedef AAlias = A;
typedef IntAlias = int;
typedef StringAlias = String;
```

**Comment by scheglov** [comment]
The same for tests that use `LanguageFeatures/nnbd/weak/type-aliases/type_reification_legacy_aliases_lib.dart`.
```dart
// @dart=2.6

library type_reification_legacy_lib;

class A {}
typedef AliasA = A;

class A1 extends A {}
class B<T>         {}
```

**Comment by sgrekhov** [comment]
@eernstg AFAIU we need to delete such tests. We  cannot have type aliases in an opted out libraries. Please confirm.

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/co19/issues/1028#issuecomment-803893349: Yes, we should delete all tests in co19_2 that depend on an experiment which wasn't enabled by default in language version 2.11 (such as nonfunction-type-aliases).

It is not completely true that we cannot have non-function type aliases in a library that does not enable null safety: It is always an error to _declare_ such a type alias in an opted-out library, but it is allowed to declare it in an opted-in library and _use_ it in an opted-out library.

That situation does not arise in co19_2, however, because every test in co19_2 is expected to consist exclusively of opted-out libraries.

**Comment by scheglov** [comment]
Note, that I was referring `co19/` tests, not `co19_2/` (I have not looked if we have anything there).
I'm running `tools/test.py -n analyzer-asserts-weak-mac co19/LanguageFeatures/nnbd/weak/type-aliases/`.
This has `12` failing tests currently.

**Comment by eernstg** [comment]
> Note, that I was referring `co19/` tests, not `co19_2/`

OK. [Current Results](https://dart-ci.firebaseapp.com/current_results/#/filter=co19/LanguageFeatures/nnbd/weak/type-aliases) shows 13 failing tests at this point, in 39 configurations. It's consistently failing with the 3 configurations `analyzer-asserts-weak-{linux,mac,win}` and passing in all other configurations, because of an unexpected CompileTimeError.

The error `SYNTACTIC_ERROR.INVALID_GENERIC_FUNCTION_TYPE` is reported for non-function type aliases (as expected), and we get some derived errors `COMPILE_TIME_ERROR.INVALID_ASSIGNMENT` because the type alias is taken to denote the type `dynamic Function()` (OK, that particular behavior isn't self-explanatory ;-).

This covers the following tests / helper libraries:

```
co19/LanguageFeatures/nnbd/weak/type-aliases/legacy_libraries_A01_t04
co19/LanguageFeatures/nnbd/weak/type-aliases/null_promotion_A01_t05
co19/LanguageFeatures/nnbd/weak/type-aliases/legacy_library_aliases_lib, used from
    co19/LanguageFeatures/nnbd/weak/type-aliases/null_promotion_A01_t05,
    co19/LanguageFeatures/nnbd/weak/type-aliases/null_promotion_A01_t10,
    co19/LanguageFeatures/nnbd/weak/type-aliases/null_promotion_A02_t06,
    co19/LanguageFeatures/nnbd/weak/type-aliases/null_promotion_A02_t08,
    co19/LanguageFeatures/nnbd/weak/type-aliases/nullability_definitions_A02_t12,
    co19/LanguageFeatures/nnbd/weak/type-aliases/nullability_definitions_A02_t19,
    co19/LanguageFeatures/nnbd/weak/type-aliases/syntax_A06_t04,
    co19/LanguageFeatures/nnbd/weak/type-aliases/syntax_A07_t04
co19LanguageFeatures/nnbd/weak/type-aliases/type_reification_legacy_aliases_lib, used from
    co19/LanguageFeatures/nnbd/weak/type-aliases/type_reification_A01_t05,
    co19/LanguageFeatures/nnbd/weak/type-aliases/type_reification_A01_t06
```

One test fails because it expects a static type warning, but use `/// static type warning` rather than `// [analyzer] STATIC_WARNING.INVALID_NULL_AWARE_OPERATOR`:

```
co19/LanguageFeatures/nnbd/weak/type-aliases/null_aware_operator_A17_t02
```

Finally we have one case where the CFE gets a MissingCompileTimeError status:

```
co19/LanguageFeatures/nnbd/weak/type-aliases/static_errors_A15_t04
```

Those are genuine issues with the CFE, cf. https://github.com/dart-lang/sdk/issues/45423.

**Comment by leafpetersen** [comment]
What is the status here?  What tests are still bad and what have been resolved?

**Comment by sgrekhov** [comment]
@leafpetersen I'm working on it now
