### ISSUE TITLE
Update the value in Language/Expressions/Shift/integer_t03.dart to be compatible with dart on the web

### ISSUE THREAD

**Issue by nshahan** [dart-lang/co19#1024]
Current the web backends (dart2js and ddc) have the compile time error:

```
tests/co19/src/Language/Expressions/Shift/integer_t03.dart:22:11:
Error: The integer literal 0x7FFFFFFFFFFFFFFF can't be represented exactly in JavaScript.
  int j = 0x7FFFFFFFFFFFFFFF;
          ^^^^^^^^^^^^^^^^^^
Error: Compilation failed.
```

If tests contain numeric literals that can not be represented exactly in JavaScript because they are too large then we lose all coverage of the cases in that test file.

Could this test be adapted to use `0x7FFFFFFFFFFFFFFF` when running on the dart vm and `0x7FFFFFFFFFFFF000` otherwise?

**Comment by sgrekhov** [comment]
Tests
Language/Expressions/Shift/integer_t01.dart
Language/Expressions/Shift/integer_t02.dart
Language/Expressions/Shift/integer_t03.dart
fixed to be able to work on JS. Work with big numbers moved to 
Language/Expressions/Shift/integer_t06.dart
Language/Expressions/Shift/integer_t07.dart

These last two tests are skipped on JS. See
https://dart-review.googlesource.com/c/sdk/+/192140

**Comment by rakudrama** [comment]
The fix is not quite right since on the web, shifts are based on 32-bit operations.
They always return non-negative results.

`a >> n` shifts in `0` bits if `a` is non-negative, and the most significant bit of the low 32 bits if `a` is negative.

These two receiver values have the same low 32 bits:
```
0x80000000     >> 8    -->    0x00800000
(-0x80000000)  >> 8    -->    0xFF800000

0x100000000    >> 24   -->    0
(-0x100000000) >> 24   -->    0
```

If the input is in the range `0...0xFFFFFFFF` the web operation `a >> n` gives the same answer as on the VM.
If the input is in the range `-0x80000000...0xFFFFFFFF` the web operation `a >> n` gives the same answer as `(a >> n).toUnsigned(32)` on the VM.

`a >> 60` will always be `0xFFFFFFFF` (for some negative numbers) or `0` (for other negative numbers and all non-negative numbers).

left shifts `a << n` give the same answer as `(a << n).toUnsigned(32)` on the VM.

**Comment by sgrekhov** [comment]
@rakudrama thank you for the explanation. It should work now
