### ISSUE TITLE
Incorrect co19_2/LanguageFeatures/Extension-methods/explicit_extension_member_invocation_A16_t09

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/co19#1028]
This test has the following code:

```dart
  C c = C();
  Extension1(c)[13] >>>= 42;
```

and
```dart
extension Extension1 on C {
  C operator [](int index) {
    this.value += index + 1;
  }
```

`operator []` in Extension1 doesn't return a value, meaning it implicitly returns `null`. Then, calling `operator >>>` on `null` results in NoSuchMethodError.

**Comment by eernstg** [comment]
But we shouldn't have any tests at all in `co19_2` using triple shift, right? It looks like we have 60 of them.

**Comment by sgrekhov** [comment]
@eernstg @alexmarkov so shall I simply remove triple shift tests from co19_2 repository? I believe they were written in co19 repository as tests for upcoming feature (triple shift) before separating to co19 and co19_2 (pre-nnbd) repositories. That's why they are there. No this issue in co19 repository

**Comment by eernstg** [comment]
> remove triple shift tests from co19_2 repository?

Yes. The triple shift feature has been available as an experimental feature for a long time (the implementation in `int` was missing, but the language feature was supported). So that made it reasonable to have these tests way back when it was possible for them to run successfully.

But it is never possible to use an experimental feature in a library whose language version is strictly smaller than the highest version supported by the tools (that is, "only the current language version can support an experiment"). This means that we simply shouldn't have any triple shift tests in co19_2.

Checking a few cases, it looks like all these tests exist in co19 / master, so they have been migrated to null safety. Hence, it should be no problem to simply delete the co19_2 triple shift tests and clean up the status files as needed.
