### ISSUE TITLE
Incorrect runtime expectations

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/co19#1039]
In these tests:

co19/LanguageFeatures/Generic-functions-as-type-args/typedef2_A02_t04 
co19/LanguageFeatures/Generic-functions-as-type-args/typedef2_A02_t03

There are runtime expectations that a generic function type is equal to a non generic function type, which will never be true.  I'm not sure what the intended assertions are here.

cc @eernstg @athomas

**Comment by eernstg** [comment]
This fails, I believe because the old-style type aliases omit the parameter name. Assume the following change:

```dart
typedef T TEST1<T extends void Function<TT>()>(T someName);
```

Then `exp1` is `void Function<T>() Function(void Function<T>())`, and a raw `TEST1` is `TEST1<void Function<TT>()>` which is `void Function<TT>() Function(void Function<TT>())`, and those two `Type`s should be equal.

And t03 looks similar.
