### ISSUE TITLE
Failures on [co19] LibTests/typed_data tests skipped for dart2js

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#1163]
There are new test failures on [[co19] LibTests/typed_data tests skipped for dart2js](https://dart-review.googlesource.com/c/sdk/+/209915).

The tests
```
co19/LibTest/typed_data/ByteBuffer/asInt64List_A02_t01 RuntimeError (expected Pass)
co19/LibTest/typed_data/ByteBuffer/asInt64List_A03_t01 RuntimeError (expected Pass)
co19/LibTest/typed_data/Int32x4/operator_OR_A01_t01 RuntimeError (expected Pass)
co19/LibTest/typed_data/Int32x4/operator_OR_A01_t01 RuntimeError (expected Pass)
```
are failing on configurations
```
dart2js-hostasserts-strong-linux-x64-chrome
dart2js-hostasserts-weak-linux-x64-chrome
```

**Comment by iarkh** [comment]
CL with the changes is sent to review.
https://dart-review.googlesource.com/c/sdk/+/209915

**Comment by athomas** [comment]
co19/LibTest/typed_data/Int32x4/operator_OR_A01_t01 is still failing on dart2js, is that one supposed to be skipped as well?

**Comment by eernstg** [comment]
I believe that one has been written to work with both native and web numbers (because it uses an `toInt32` function to process various intermediate results). I created https://github.com/dart-lang/co19/issues/1164 to explain why it needs a serious fix.

For co19/LibTest/typed_data/ByteBuffer/asInt64List_A02_t01 I'd assume that it should be skipped on web configurations because they do not implement `Int64List`: https://dart.dev/faq#q-how-are-typed-lists-handled-when-compiled-to-javascript.

**Comment by iarkh** [comment]
#1164 has been fixed.
