### ISSUE TITLE
Some "Lexical_Rules" (and similar) tests needs updating after SDK CL lands

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/co19#1169]
With https://github.com/dart-lang/sdk/commit/7399e4e6313a9b5e3a7bbf0a40ba34642848072b the following tests needs updating:

co19_2/Language/Expressions/This/placement_t02
co19_2/Language/Reference/Lexical_Rules/Reserved_Words/assert_t08
co19_2/Language/Reference/Lexical_Rules/Reserved_Words/break_t08
co19_2/Language/Reference/Lexical_Rules/Reserved_Words/continue_t08
co19_2/Language/Reference/Lexical_Rules/Reserved_Words/do_t08
co19_2/Language/Reference/Lexical_Rules/Reserved_Words/else_t08
co19_2/Language/Reference/Lexical_Rules/Reserved_Words/for_t08
co19_2/Language/Reference/Lexical_Rules/Reserved_Words/if_t08
co19_2/Language/Reference/Lexical_Rules/Reserved_Words/return_t08
co19_2/Language/Reference/Lexical_Rules/Reserved_Words/switch_t08
co19_2/Language/Reference/Lexical_Rules/Reserved_Words/this_t08
co19_2/Language/Reference/Lexical_Rules/Reserved_Words/try_t08
co19_2/Language/Reference/Lexical_Rules/Reserved_Words/while_t08

co19/Language/Expressions/This/placement_t02
co19/Language/Reference/Lexical_Rules/Reserved_Words/assert_t08
co19/Language/Reference/Lexical_Rules/Reserved_Words/break_t08
co19/Language/Reference/Lexical_Rules/Reserved_Words/continue_t08
co19/Language/Reference/Lexical_Rules/Reserved_Words/do_t08
co19/Language/Reference/Lexical_Rules/Reserved_Words/else_t08
co19/Language/Reference/Lexical_Rules/Reserved_Words/for_t08
co19/Language/Reference/Lexical_Rules/Reserved_Words/if_t08
co19/Language/Reference/Lexical_Rules/Reserved_Words/return_t08
co19/Language/Reference/Lexical_Rules/Reserved_Words/switch_t08
co19/Language/Reference/Lexical_Rules/Reserved_Words/this_t08
co19/Language/Reference/Lexical_Rules/Reserved_Words/try_t08
co19/Language/Reference/Lexical_Rules/Reserved_Words/while_t08

**Comment by sgrekhov** [comment]
@jensjoha on the edge version of the SDK these tests fail in CFE but work in analyzer. Do we expect appropriate change in the analyzer as well? Need these tests to be changed to expect a new behavior from the analyzer as well (they will fail for now then)?

**Comment by jensjoha** [comment]
I believe this is a CFE change only (for the purpose of these tests) --- these tests are all of the same type: a method f is specified with one parameter with an invalid name and a call to that method with one parameter.

The CFE apparently before turned that into a method with no parameters, which then gave an error when calling it with 1 parameter instead of 0. The Analyzer seems to never have complained about the call so has likely done it correctly from the start (by creating a method f taking 1 parameter).

The parser change I've landed has caused the CFE to create f as a method taking one parameter and the error at the call site thus disappear.

**Comment by eernstg** [comment]
We do not specify how to deal with derived errors, also known as errors-on-errors: Situations where we test the error properties of a term that uses declarations that already have an error. Basically, we do not put any restrictions on the approach to error recovery. This means that both erasing the parameter and repairing the parameter is a perfectly valid error recovery, and the specification has no opinion about which one to prefer.

So the durable approach to this situation is simply that we don't test how errors-on-errors are handled. 

In this case we might use `print(f)` to ensure that `f` isn't eliminated during compilation (because it's unused), because we will then avoid depending on the shape of its parameter list.
