### ISSUE TITLE
Tests covering: Invalid Dart code with FFI should have compile time errors not crash the compiler

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/co19#1237]
I don't think we have too many tests that cover that the FFI transform in the CFE does not crash on invalid Dart code. Could we add more co19 tests covering the compile-time errors to ensure we emit compile time errors instead of crashing in the compiler?

context:

* https://github.com/dart-lang/sdk/issues/47673
* https://dart-review.googlesource.com/c/sdk/+/220760 (adds tests that ensure that we emit a compile time error rather than having the compiler crash)

cc @sgrekhov

**Comment by sgrekhov** [comment]
@dcharkes I'll add tests that check that it is a compile time error if `Array` has a wrong type. I don't think that it makes sense to try to cover more cases. 'Invalid Dart code' is too wide concept, the code may be invalid because of infinity number of reasons, including syntax errors, variables and classes with the same names, subtyping or nullability violence etc. That gives us almost infinite number of tests cases and we can't cover all of them. We have general concept 'if the code is wrong then it must be a compile time error'. But we don't try to test all of the possible cases, there are too much of them
