### ISSUE TITLE
co19 enhanced enums test triage: bad tests

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/co19#1333]
The following tests have errors or incorrect expectations:
  - co19/LanguageFeatures/Enhanced-Enum/implementing_enum_A03_t04 has an extraneous cfe error expectation
  - co19/LanguageFeatures/Enhanced-Enum/implementing_enum_A01_t06 causes CFE failures since the CFE reports two (arguably valid) errors per class (the index member is arguably extraneous to this test?)
  - co19/LanguageFeatures/Enhanced-Enum/implementing_enum_A01_t04 same issue as the previous
  - co19/LanguageFeatures/Enhanced-Enum/implementing_enum_A01_t01 same issue as the previous
  - co19/LanguageFeatures/Enhanced-Enum/grammar_A07_t01 causes additional tool errors on the web compilers where there are restrictions on "external".  These should either be skipped, or updated with the web compiler error expectations.
  - co19/LanguageFeatures/Enhanced-Enum/semantics_A11_t01 error expectation locations do not match up with the locations used by the CFE (which seem valid choices).
  - co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t06 error expectations need adjustment (cfe reports different but valid location)
  - co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t04 as above
  - co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t03 bad error expectation locations
  - co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t02 extraneous error expectations
  - co19/LanguageFeatures/Enhanced-Enum/semantics_A06_t07 cfe reports follow on errors (which seem valid to report)
  - co19/LanguageFeatures/Enhanced-Enum/grammar_A06_t01 cfe error expectations are in the wrong location (it reports on class)
  - co19/LanguageFeatures/Enhanced-Enum/grammar_A05_t01 cfe reports additional (but reasonable) follow on errors
  - co19/LanguageFeatures/Enhanced-Enum/grammar_A01_t02 cfe reports additional (but reasonable) follow on errors

cc @johnniwinther @chloestefantsova @eernstg @lrhn

**Comment by eernstg** [comment]
Here's the current status (concerning test run failures; for a characterization of the reasons for these failures, please check the initial comment in this issue):

No failures:

- co19/LanguageFeatures/Enhanced-Enum/semantics_A11_t01
- co19/LanguageFeatures/Enhanced-Enum/grammar_A06_t01

Fails on the CFE:

- co19/LanguageFeatures/Enhanced-Enum/grammar_A01_t02
- co19/LanguageFeatures/Enhanced-Enum/grammar_A05_t01
- co19/LanguageFeatures/Enhanced-Enum/implementing_enum_A01_t01
- co19/LanguageFeatures/Enhanced-Enum/implementing_enum_A01_t04
- co19/LanguageFeatures/Enhanced-Enum/implementing_enum_A01_t06
- co19/LanguageFeatures/Enhanced-Enum/implementing_enum_A03_t04
- co19/LanguageFeatures/Enhanced-Enum/semantics_A06_t07
- co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t02
- co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t03
- co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t04
- co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t06

Fails on dart2js, DDC:

- co19/LanguageFeatures/Enhanced-Enum/grammar_A07_t01

@athomas, @chloestefantsova, this seems to imply that the changes in #1330 and #1331 have not yet been rolled into the SDK, or they did not eliminate all failures. Is this also the expected status?

It looks like the remaining CFE-failing tests just need to be adjusted such that they expect the errors reported by the CFE (which are already reasonable according to the characterization by @leafpetersen):

- co19/LanguageFeatures/Enhanced-Enum/grammar_A01_t02
- co19/LanguageFeatures/Enhanced-Enum/grammar_A05_t01
- co19/LanguageFeatures/Enhanced-Enum/implementing_enum_A03_t04
- co19/LanguageFeatures/Enhanced-Enum/semantics_A06_t07
- co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t04
- co19/LanguageFeatures/Enhanced-Enum/semantics_A09_t06

'grammar_A07_t01' needs to be skipped by web compilers (because they do not support the `external` declarations used in these tests). We could also change the test to expect this special error, but presumably that's tested elsewhere already. Cf. https://dart-review.googlesource.com/c/sdk/+/240046.

**Comment by chloestefantsova** [comment]
Yes, I believe most of the tests await for the roll into the SDK. I also landed a few CLs to adjust the locations the CFE reports errors on, so I'll look into the co19 tests once more after the roll.

**Comment by chloestefantsova** [comment]
With the latest PR fixing the remainder of the tests (https://github.com/dart-lang/co19/pull/1336), I believe we can close this issue. Please reopen if needed.
