### ISSUE TITLE
It is a compile-time error if a function contains both one or more explicit return statements of the form \code{\RETURN;} and one or more return statements of the form \code{\RETURN{} $e$;}.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#157]
Tests:
co19_2/Language/Statements/Return/many_return_statements_t01

https://github.com/dart-lang/sdk/blob/4b8d3e4cf133c7c2f980e2d3894e44e041907453/docs/language/dartLangSpec.tex#L8760

**Comment by eernstg** [comment]
Hello @scheglov, it is unfortunately one step too far to take the wording in the spec and enforce it as-is.

For years, in addition to the language specification `dartLangSpec.tex`, we have had feature specifications [here (with status 'Under implementation' or 'Implemented')](https://github.com/dart-lang/sdk/tree/master/docs/language/informal) and, since the 'language' repo was created, [here](https://github.com/dart-lang/language/tree/master/accepted), and they must be taken into account.

In particular, [invalid_returns.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/invalid_returns.md) specifies which return statements are accepted, and those rules override the ones in `dartLangSpec.tex` such that it _is_ allowed to have a function that has one or more `return;` as well as one or more `return e;` statements, as long as each of them satisfies the rules in that feature spec.

The example you mention, `co19_2/Language/Statements/Return/many_return_statements_t01`, is one example of such a situation: It is allowed, and the test should be updated to expect no errors.

We are continuously integrating the feature specs into `dartLangSpec.tex` and marking the feature specs that have been integrated as 'background' materiel (in the status). In the language repo we have the `accepted` directory, and we don't yet have a specific way to indicate that a feature spec from there has been integrated into `dartLangSpec.tex` (that I know of), but it's likely that we will move such specs to a directory named `background` such that `accepted` specs are the ones that have to be taken into account.

However, this particular example is a very good illustration of why it is a non-trivial task to integrate each feature spec into `dartLangSpec.tex`, and also how this work is done in multiple steps. You cited line 8760 above; if you look at lines 8758-8759 in `dartLangSpec.tex` you'll see a comment which says exactly what we're talking about here: The sentence in line 8760 is invalidated by `invalid_returns.md`.

So (1) thanks for looking into this, it's very helpful to get tests updated with the right expectations, but (2) please check the active feature specs (or check it with the language team) before initiating any changes like this. Thanks again!

**Comment by eernstg** [comment]
The update where the sentence mentioned [here](https://github.com/dart-lang/co19/issues/157#issue-354554599) has been deleted took place in 9388cb3d0c3788ee37f84eddb6bff8e7a6bace62.

This eliminates one discrepancy between `dartLangSpec.tex` and the effective language specification (which must also take all the feature specs into account), but there are others. Hence, it is still relevant to take the feature specs into account.

**Comment by bwilkerson** [comment]
Is there a time frame for when all of the feature specifications will be rolled into the specification so that we can have a single source of truth?

**Comment by eernstg** [comment]
It is planned to finish a Dart 2.1 spec in 2018 where all feature specifications (except the upcoming ones for type inference) are integrated.

**Comment by sgrekhov** [comment]
No action required. Closed
