### ISSUE TITLE
DateTime.parse now can support microseconds

### ISSUE THREAD

**Issue by floitschG** [dart-lang/co19#17]
LibTest/core/DateTime/parse_A01_t02 tests that the microseconds are rounded into the milliseconds.
I just added support for microseconds (to the VM at least), and this is no longer true.

Since that behavior is not supported by the dart2js compiler, please separate microsecond tests from other tests (so that dart2js can mark the microsecond tests as failing without losing coverage for the other parse tests).

**Comment by sgrekhov** [comment]
Will add microseconds test as sson as Dart API specification will be updated. The latest available (for me) api spec https://api.dartlang.org/1.13.1/dart-core/DateTime-class.html doesn't contain microseconds support. If you know where can I find updated Dart API spec with microseconds support please let me know

**Comment by floitschG** [comment]
Sorry. Didn't specify when microsecond support will be available.
The next public release, 1.14, will contain microsecond support. Nightly builds already contain the change. They are available here:
http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/

**Comment by sgrekhov** [comment]
@floitschG I started writing tests for microseconds and found that now time is not rounded to microseconds.  Before microseconds support time was rounded up to milliseconds. For example
`"2001-01-01 00:00:00.999499"` was rounded up to `"2001-01-01 00:00:00.999"`. But for microseconds time is not rounded but throws an exception. For example an attempt to parse string `"2001-01-01 00:00:00.9994991"` produces
```
FormatException: Invalid date format
2001-01-01 00:00:00.9994991
```
Is this intended? I'd expect rounding or just truncating rather than exception

**Comment by floitschG** [comment]
In the parse-function we only support 6 digits after the ".".
We could change that, but I don't think it's necessary. The reason for allowing 6 digits was, because some platforms already supported microseconds, and we wanted to be able to read them in (even though we lost some precision). I don't think we need to allow more than that (and we could relax it in the future if we really think it's necessary).

**Comment by sgrekhov** [comment]
Fixed. 8465825f60c9580d82ae01ffc040f3b589aaf667 and 5f4d8e394c7505a684b31f7455847c55f1419132
