### ISSUE TITLE
LibTest/io/HttpServer/close_A05_t01.dart is bad

### ISSUE THREAD

**Issue by mraleph** [dart-lang/co19#172]
It does this:

```dart
  HttpServer server = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
  int port = server.port;
  server.close(force: true);
  server = await HttpServer.bind(InternetAddress.loopbackIPv4, port);
```

There are two obvious issues with this test:

First of all there is a missing await for the result of `server.close(...)` - closing sockets is an asynchronous operation so you need to wait for close to complete before trying to rebind to the same port again;

Second - in a shared testing environment (e.g. when many tests are run in parallel) there might be a race for the port anyway and somebody will bind to this port preventing `HttpServer.bind` from succeeding.

**Comment by sgrekhov** [comment]
@mraleph I fixed the first issue. It was definitely a bug, thank you for pointing. As for the second issue, test checks that `.close()` frees the port and it can be used again. Of course, in a shared environment, there is a probability that the port just freed by `close()` is immediately binded again by another process and test fail. But let's see if it really will be a problem. Otherwise I had to simply delete the test. Please let me know your opinion
