### ISSUE TITLE
co19_2/LibTest/io/Stdin/readLineSync_A03_t02 flaky failures on Mac

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/co19#184]
Here is an example:

https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/vm-kernel-mac-product-x64/704

**Comment by mkustermann** [comment]
@sjindel-google When filing a co19 issue it is very much beneficial to actually look at the test and see why it is flaky and determine if the flakiness is actually caused by the test itself!

It appears to me from [LibTest/io/Stdin/readLineSync_A03_t02](https://github.com/dart-lang/co19/blob/master/LibTest/io/Stdin/readLineSync_A03_t02.dart#L29):
```dart
void run_process(String filename, Encoding enc) {
  String res = stdin.readLineSync(encoding : enc);
  File fl = new File(filename);
  fl.openWrite();
  fl.writeAsBytes(res.codeUnits);
}
```

Two issues stick out here:

* The `fl.openWrite()` opens the file and returns an `IOSink`, this returned sink is never used for anything!
* The `writeAsBytes` method is asynchronous and the process does not await it's return value.

I would suggest using one of these two methods and waiting for the operation to be completed:
```dart
runProcess(String filename, Encoding enc) async {
  String res = stdin.readLineSync(encoding : enc);
  File fl = new File(filename);

  // Either
  final sink = fl.openWrite();
  sink.add(res.codeUnits);
  await sink.close();

  // Or
  await fl.writeAsBytes(res.codeUnits);
}
```

**Comment by iarkh** [comment]
FIXED
