### ISSUE TITLE
Possibly unintended runtime error in patterns tests

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#1896]
In the following tests the first positional argument to the invocations of `getType` is cast to the inferred type argument of the invocation. However, the type of the first formal positional parameter of `getType` is `Object?`, which leads to a difference between the inferred type argument to `getType` and the inferred type argument to `[]` passed as the first positional argument.

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A07_t01.dart#L53

The stack trace is as follows:

```
stderr:
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'List<C>' in type cast
#0      getType (file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/patterns_lib.dart:47:12)
#1      main (file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/type_inference_A07_t01.dart:64:15)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

Another similar case is the following:

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A08_t01.dart#L49

**Comment by eernstg** [comment]
Looks like [`getType`](https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/patterns_lib.dart#L42) should be adjusted to have type `T` rather than `Object?` for the first formal parameter.

The point is that `getType` can "measure" the context type schema (or at least its greatest closure), in order to verify that the initializing expression gets the right context type schema. But at run time we should also have an object with that type, and `Object?` won't communicate the value of `T` to the actual argument. So we can specify the type arguments explicitly on that first argument, or we can change `getType` to give `{}` that context type, whatever works.

**Comment by alexmarkov** [comment]
`LanguageFeatures/Patterns/type_inference_A08_t01` was mentioned above but it wasn't fixed:

https://github.com/dart-lang/co19/blob/5463a0b9331476a031714479f646a4c462ec9edb/LanguageFeatures/Patterns/type_inference_A08_t01.dart#L49
