### ISSUE TITLE
Mismatching top type in expectations in inference tests for the patterns feature

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#1897]
In the following tests the CFE infers `Object?` instead of `dynamic` as expected in the tests. I'm not sure which one conforms to the language specification, so this issue is more of a question, which one of the two types should be inferred.

1. "List<dynamic>" vs "List<Object?>"

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A07_t02.dart#L42

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A07_t02.dart#L46

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A07_t05.dart#L40

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A07_t05.dart#L43

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A07_t05.dart#L46

2. "Map<dynamic, dynamic>" vs "Map<Object?, Object?>"

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A08_t02.dart#L25

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A08_t02.dart#L29

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A08_t03.dart#L54

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A08_t03.dart#L61

3. "Map<dynamic, B>" vs "Map<Object?, B>"

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A08_t03.dart#L40

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A08_t03.dart#L47

**Comment by eernstg** [comment]
I think all the tests should be adjusted to expect `Object?` rather than `dynamic`.

This is consistent with [this bullet](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#:~:text=Otherwise%20the%20solution%20is%20the%20greatest%20closure%20of%20Mt%20with%20respect%20to%20_.):

> Otherwise the solution is the greatest closure of `Mt` with respect to `_`.

and [this rule](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#:~:text=The%20greatest%20closure%20of%20S%20with%20respect%20to%20L%20is%20Object%3F) where `S` is a type variable `X` which is included in the set `L` (and `_` is treated as a type variable):

> The greatest closure of `S` with respect to `L` is `Object?`

So I'd expect type inference to come up with `Object?` when there are no constraints, but I also think there is some ambiguity in practice (so we get `dynamic` in some cases where I'd expect `Object?`).

Changing every one of these tests where `dynamic` is expected such that it expects `Object?` would then be an adjustment to expect the specified behavior, which would be a good thing.

Just as an illustration of the status, here is an example where I would expect type inference to choose `Object?`, but we actually get `dynamic`:

```dart
class C<X> {}

void main() {
  var x = C();
  print(x.runtimeType); // Prints 'C<dynamic>'.
}
```

**Comment by eernstg** [comment]
3.0 might be a good time to take a step forward: Fewer locations in types have the value `dynamic`, because inference will choose `Object?` as specified in more cases.

It might cause a substantial amount of compile-time breakage, though...

**Comment by leafpetersen** [comment]
> I think all the tests should be adjusted to expect Object? rather than dynamic.

Agreed.  As discussed offline with @nshahan , this isn't actually a new inconsistency.  As part of null safety, we changed greatest/least closure to use `Object?` as the top type instead of `dynamic`, and this behavior just falls out of it.  It's true that this makes places that use greatest/least closure inconsistent with places in inference that use instantiate to bounds, but the latter was considered too breaking. You can see the internal consistency via the following examples:

```dart
T getType<T>(Object? o,
    [void Function(String s)? logger = null]) {
  if (logger != null) {
    logger(T.toString());
  }
  return o as T;
}

void foo<T>(List<T> t) {}

void main() {
  var [] = getType([], (String s) {print(s);});
  foo(getType([3], (String s) {print(s);}));
}
```
