### ISSUE TITLE
LanguageFeatures/Patterns/execution_pattern_for_in_element_A01_t03.dart

### ISSUE THREAD

**Issue by nshahan** [dart-lang/co19#1930]
There are three expected errors in this test that I'm not sure should be errors.

https://github.com/dart-lang/co19/blob/11b06deb80243095ffd0dfc338623b646dcb7c36/LanguageFeatures/Patterns/execution_pattern_for_in_element_A01_t03.dart#L42

https://github.com/dart-lang/co19/blob/11b06deb80243095ffd0dfc338623b646dcb7c36/LanguageFeatures/Patterns/execution_pattern_for_in_element_A01_t03.dart#L61

https://github.com/dart-lang/co19/blob/11b06deb80243095ffd0dfc338623b646dcb7c36/LanguageFeatures/Patterns/execution_pattern_for_in_element_A01_t03.dart#L67

Each of these expect there to be a runtime error when destructuring but I think in these cases they all get runtime casts inserted that pass without issue. All the `num`s are in fact `int`s at runtime.

The other expectations in the file do have errors because the difference between the `num`s and `int`s are embedded into the reified generic type arguments so the casts do fail at runtime. For example casting a `List<num>` as a `List<int>`.

@eernstg Could you confirm?

**Comment by nshahan** [comment]
Similar problems appear in https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Patterns/execution_pattern_for_in_statement_A01_t03.dart.

**Comment by eernstg** [comment]
That is true. I probably got that wrong during reviews. ;-) In any case, the given tests have the following description:

> Checks that if `I` is `dynamic` and runtime type of `I` is `Iterable<T>` where `T` is not assignable to `<pattern>` required type then a run-time error occurs

In the given cases, `I` is `dynamic`, so `E` in the specification text is also `dynamic`, so the actual run-time error occurs if the initialization `Iterator<dynamic> id2 = id1.iterator;` throws (where `id1` has type `dynamic`).

In other words, the description should say something like this:

> Checks that if `I` is `dynamic` and the run-time type of the iterable expression (whose value is stored in `id1` in the specification text) is not a subtype of `Iterable<dynamic>` then a run-time error occurs. Moreover, each element may give rise to a run-time error because `<keyword> <pattern> = id2.current;` has an initializing expression of type `dynamic`.

In the first example, every assignment to `int v1` may fail, because the element from the iterable is only known to have type `dynamic`, and it could indeed be a non-integer (for example `<Object>[2, 1.9] as dynamic` could be used to do that).
