### ISSUE TITLE
co19_2/LibTest/core/List/List_class_A01_t02 and related tests timing out on Mac for debug builds

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/co19#198]
Affected tests:
* [LibTest/collection/ListBase/ListBase_class_A01_t02](https://github.com/dart-lang/co19/blob/master/LibTest/collection/ListBase/ListBase_class_A01_t02.dart)
* [LibTest/collection/ListMixin/ListMixin_class_A01_t02](https://github.com/dart-lang/co19/blob/master/LibTest/collection/ListMixin/ListMixin_class_A01_t02.dart)
* [LibTest/core/List/List_class_A01_t02](https://github.com/dart-lang/co19/blob/master/LibTest/core/List/List_class_A01_t02.dart)

These all pull in the same file ([LibTest/core/List/hugeTestLists.dart](https://github.com/dart-lang/co19/blob/master/LibTest/core/List/hugeListTests.lib.dart)) which runs a suite of large list sorting tests from three separate imports. The combined test runs for 4-6 mins on succeeding runs, checking a few such runs, and now and again causes failures due to hitting the 8 min timeout cutoff.

If all these sorting tests are needed, they should be separated out instead of run together to avoid the combined test suite timing out sporadically, which has started to happen since [this change](https://dart.googlesource.com/sdk/+/ad7fbb6dd71f27319a281396863651b9d0936526) landed. (See [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8929045070944007280/+/steps/vm_co19_tests_shard_1/0/stdout) or [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8928800738602815136/+/steps/vm_co19_tests_shard_4/0/stdout) for example timeouts).

**Comment by dcharkes** [comment]
See the analysis in https://github.com/dart-lang/sdk/issues/35297.

The short term solution is to split these tests into separate tests instead of combine them, and to split [LibTest/core/List/sort_A01_t06.test.dart](https://github.com/dart-lang/co19/blob/master/LibTest/core/List/sort_A01_t06.test.dart) into 3 tests. This way the functionality of the lists can be tested without slowdowns.

Separately, the performance degradation when tests are combined should be investigated: https://github.com/dart-lang/sdk/issues/35297
