### ISSUE TITLE
invalid test: set_literals_A03_t01/03 and /04

### ISSUE THREAD

**Issue by whesse** [dart-lang/co19#220]
This is a test that 
 var v3 = <B> {new B(), new C(), new A()};
is a static error, if B is a subclass of A and C is a subclass of B.
But the specification only requires that the types be assignable, not subclasses.  And A is assignable to B.

The tests LanguageFeatures/Set-literals/set_literals_A03_t01 and LanguageFeatures/Set-literals/set_literals_A03_t02 are incorrect.

you could imagine a factory constructor of class A that returns a B, for example, which would be correct statically and at runtime.

I'm not sure if the specification shouldn't be tighter for constants,

Is this test right about the specification?

@bwilkerson @eernstg

**Comment by eernstg** [comment]
The test should be kept as it is. The errors for `v3` and `v4` arise due to the exact type of `new A()` and `const A()`.

**Comment by eernstg** [comment]
You could say that the comment is misleading because it talks about 'assignable' and this is specified to include being-a-supertype-of; but we might end up folding exact types into the notion of assignability, such that `exactly A` is not assignable to `B`, even though `B <: A`. So it would be helpful to mention the role played by exact types in a comment somewhere.

**Comment by sgrekhov** [comment]
According to Erik - closed
