### ISSUE TITLE
Test expects too many errors

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/co19#2224]
There are new test failures on [[parser] Add error recovery to extension type declaration parsing](https://dart-review.googlesource.com/c/sdk/+/321704).

The tests
```
co19/LanguageFeatures/Extension-types/syntax_A04_t01 MissingCompileTimeError (expected Pass)
```
are failing on configurations
```
cfe-strong-linux
cfe-weak-linux
```
The CFE now (a likely analyzer soon) handles extension type declarations without a primary constructor declaration and therefore no longer reports an error on the use of the extension type as a type literal.

**Comment by eernstg** [comment]
We might want to make the treatment of secondary errors explicit: If there is an error which is caused by a different error (i.e., the former error is a "secondary" error) then the response from each tool is an unspecified behavior (in other words, each tool can do whatever it wants).

In this case we should just detect which behaviors the tools exhibit, and then expect that behavior, no matter what it is.

This means that it could be useful to have a standardized comment on each secondary error, such that future work on the same code could immediately re-establish the awareness of the need to expect whatever the tool does. Perhaps we could use something along the lines of this:

```dart
main() {
  print(ET);
//      ^^
// [analyzer] unspecified
// [cfe] unspecified
// Secondary error: just expect whatever the tool does.
}
```

In this case we would probably remove the `[cfe]` line soon, and later the `[analyzer]` line, in which case the error expectation goes away entirely. But we might as well get into a habit of marking secondary errors explicitly, because they are so special (and hopefully we only have few of them).

**Comment by sgrekhov** [comment]
@eernstg I like this idea to explicitly mark secondary errors. But the way suggested above breaks infra. It produces 
`FormatException: Invalid error expectation syntax`

**Comment by eernstg** [comment]
OK, we can just keep the idea in mind --- it seems wasteful to have to re-discover that a particular expectation is 'secondary error'-ish, because they are easy to fix if they ever start failing.
