### ISSUE TITLE
Wrong static type on ==

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/co19#2369]
The test `co19/LanguageFeatures/Extension-types/static_analysis_member_invocation_A01_t05` assumes that the static type of `==` can be derived from the return type of the declared `operator ==` method:

```
class B implements A {
  ...
  @override
  BoolET operator ==(Object? other) => BoolET(other == this);
}
...
extension type ET2(B b) implements ET1, B {}

extension type BoolET(bool b) implements bool {}

void main() {
  var e2 = ET2(B());
  ...
  BoolET b2 = e2 == e2;
}
```
Here `e2.==` can be found to have type `BoolET Function(Object?)` as declared in `B`.

If the latest spec is to be believed, the static type of an equality expression is always defined to be `bool`: (§17.27: "The static type of an equality expression is bool.")

cc @eernstg

**Comment by eernstg** [comment]
Right, an equality expression has the type `bool` no matter what the declaration of the member named `==` says. I guess the reason is that an equality expression does more than just call operator `==` on the left hand operand (it performs a couple of tests for null).

This means that "treated as all other non-extension type members" in the test description is true even for `==`. However, an expression of the form `e1 == e2` is given an unusual treatment in all cases (when it occurs in the interface of the class `B`, and also when it occurs in the interface of the extension type `ET2`).

It would probably be helpful for future readers to add a comment like '// The type of an equality expression is always `bool`.' just before `bool b2 = e1 == e2;`.
