### ISSUE TITLE
Spread tests contain redundant keys, which is a compile-time error

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/co19#246]
```
ERROR|STATIC_WARNING|EQUAL_KEYS_IN_MAP|/b/s/w/ir/cache/builder/sdk/tests/co19_2/src/LanguageFeatures/Spread-collections/DynamicSemantics_Map_A02_t08.dart|37|44|1|Two keys in a map literal can't be equal.
ERROR|STATIC_WARNING|EQUAL_KEYS_IN_MAP|/b/s/w/ir/cache/builder/sdk/tests/co19_2/src/LanguageFeatures/Spread-collections/DynamicSemantics_Map_A02_t08.dart|40|45|1|Two keys in a map literal can't be equal.
```

and

```
ERROR|STATIC_WARNING|EQUAL_KEYS_IN_MAP|/b/s/w/ir/cache/builder/sdk/tests/co19_2/src/LanguageFeatures/Spread-collections/DynamicSemantics_Map_A02_t07.dart|41|15|2|Two keys in a map literal can't be equal.
ERROR|STATIC_WARNING|EQUAL_KEYS_IN_MAP|/b/s/w/ir/cache/builder/sdk/tests/co19_2/src/LanguageFeatures/Spread-collections/DynamicSemantics_Map_A02_t07.dart|48|15|2|Two keys in a map literal can't be equal.
ERROR|STATIC_WARNING|EQUAL_KEYS_IN_MAP|/b/s/w/ir/cache/builder/sdk/tests/co19_2/src/LanguageFeatures/Spread-collections/DynamicSemantics_Map_A02_t07.dart|37|52|2|Two keys in a map literal can't be equal.
ERROR|STATIC_WARNING|EQUAL_KEYS_IN_MAP|/b/s/w/ir/cache/builder/sdk/tests/co19_2/src/LanguageFeatures/Spread-collections/DynamicSemantics_Map_A02_t07.dart|44|52|2|Two keys in a map literal can't be equal.
```

**Comment by iarkh** [comment]
Fixed.
BTW - Am I correct that two duplicated spread map literals should cause compile time error?
For example:
``` dart
Map map = {};
Map map1 = {...map, ...map};
```
Should I add such a test?

**Comment by eernstg** [comment]
Drive-by comment: The run-time map literal `{...map, ...map}` is not an error, it is never an error (in a non-constant map) to have duplicated keys (and the 'value' part of a map entry is never required to be different from other value parts). It will just overwrite the existing entry.

We have one extra level of subtlety here because we're considering two spreads, but for the run-time map there is nothing new: If the two spreads happen to yield some map entries with the same key then the non-first ones would simply overwrite the existing entry in `map1`.

If `map1` had been constant then it would have been an error to have duplicates, but in that case there are constraints on the value of the spread which will ensure that it is possible to detect overlaps.

**Comment by MichaelRFairhurst** [comment]
Hmm, looking back at this, I'm not sure this was a correct bug to file.

I don't think this should be a compile time error. I think the analyzer has been reporting this error historically in spite of the spec.

Only constant map literals cannot have duplicate elements

**Comment by MichaelRFairhurst** [comment]
Reopened in case the fix needs to be reverted.

**Comment by eernstg** [comment]
@MichaelRFairhurst wrote:
> I don't think this should be a compile time error. .. 
> Only constant map literals cannot have duplicate elements

That's true, so if any tests are currently expecting a compile-time error for `==` keys in a run-time map, they should be adjusted to expect no error, and possibly have some code added in order to test the dynamic semantics.
