### ISSUE TITLE
Add tests that `as void` is not an expression

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/co19#2487]
> ⟨typeCast⟩ ::= ⟨asOperator⟩ ⟨typeNotVoid⟩
> ⟨asOperator⟩ ::= as
> 

It's a compile-time error if `type` is `void`. Don't forget to check type aliases

**Comment by eernstg** [comment]
Right&mdash;the type aliases denoting the type are actually OK (it is a _syntax_ error to use `void`, but `as MyVoid` where `typedef MyVoid = void;` is fine).

Yes, it is silly, but `void` only gets special treatment because it used to be very special and still is slightly special, including: it is a reserved word. Nobody cares enough to make it an ordinary identifier. ;-)
