### ISSUE TITLE
Set context type is a legal way of disambiguating empty maps: co19_2/LanguageFeatures/Spread-collections/Ambiguity_A02_t01/01

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/co19#307]
also affects co19_2/LanguageFeatures/Spread-collections/Ambiguity_A02_t02/01

```
Let *e* be a `setOrMapLiteral`.

If *e* has a context `C`, and the base type of `C` is `Cbase` (that is, `Cbase`
is `C` with all wrapping `FutureOr`s removed), and `Cbase` is not `?`, then let
`S` be the greatest closure.

...

    Else, if `S` is defined and is a subtype of `Iterable<Object>` and `S` is
    not a subtype of `Map<Object, Object>`, then *e* is a set literal.
```

In this case `S` would be `Set<dynamic>` which is a subtype of `Iterable<Object>` and *not* a subtype of `Map<Object, Object>` and therefore this code is valid and produces a Set.

The comments around backwards compatibility have a grain of truth but miss a critical part.

It used to be possible to write:

```
dynamic x = {};
```

This must be a map because it was valid code with defined behavior that we cannot violate.

However, this was not valid code before:

```
Set x = {};
```

this would have been a static error. We therefore are allowed to redefine this to being valid with the result being that we create an empty set.

Hopefully that helps explain why+how the spec accepts this.

**Comment by iarkh** [comment]
Hello, here is Ambiguity_A02_t01 source code:
``` dart
main() {
  Set res1 = {}; //# 01: compile-time error
  Map res2 = {};
}
```
Line `Set res1 = {};` is marked  with `compile-time error` keyword here, this means that static exception is expected. So could you please clarify what is wrong with this?

**Comment by eernstg** [comment]
I think the explanation from @MichaelRFairhurst does clarify the situation. In short, the `//# 01` error does not exist because the expression `{}` in that line has context `Set<dynamic>`. This means that it is inferred to be a set literal of type `Set<dynamic>`, and it is not an error to initialize a variable of type `Set<dynamic>` with an expression of that type.

**Comment by MichaelRFairhurst** [comment]
It looks like the fix (#c2b10f1) didn't include co19_2/LanguageFeatures/Spread-collections/Ambiguity_A02_t02

Apologies for having one in the title and one in the text, that surely caused the confusion.

**Comment by iarkh** [comment]
Hello,
Ambiguilty_A02_t02 now is:
``` dart
main() {
  Set res1 = {...?null};
  Map res2 = {...?null};

  var res3 = {...?null};     //# 01: compile-time error
  dynamic res4 = {...?null}; //# 02: compile-time error
}
```
Which test case is incorrect here?

**Comment by eernstg** [comment]
I believe the indicated code from `Ambiguity_A02_t02` is correct:

```dart
main() {
  Set res1 = {...?null};
  Map res2 = {...?null};

  var res3 = {...?null};     //# 01: compile-time error
  dynamic res4 = {...?null}; //# 02: compile-time error
}
```

The literal in `res1` gets the inferred type `Set<dynamic>` (and `...?null` provides the set element type `Null`, but that piece of information is not used). The literal in `res2` gets the inferred type `Map<dynamic, dynamic>` (and the key and value element types from the spread are `Null`, but ignored). The literal in `res3` hits the case 'collection is still ambiguous' and is an error because it is not true that `...?null` must be a set or must be a map. Finally, `res4` hits the same case and is also an error.

So, @MichaelRFairhurst, did you spot an error that I just missed? Or maybe this is just a matter of looking at different versions of that file?
