### ISSUE TITLE
NewOperators >>>

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#355]
1. The support for `>>>` was moved behind a new experiment flag `triple-shift`.

2. `co19_2/LanguageFeatures/Constant-update-2018/NewOperators_A01_t06/none` has an error because `MyClass(d1, -14)` evaluates `14 >>> -14`, and shifts are defined only for non-negative RHS.

3. Similar for `co19_2/LanguageFeatures/Constant-update-2018/NewOperators_A01_t04/none`.

3. `co19_2/LanguageFeatures/Constant-update-2018/NewOperators_A01_t02` has an error, because SDK does not include `int.>>>` implementation yet.

4. `co19_2/LanguageFeatures/Constant-update-2018/NewOperators_A01_t01`. Here `c2.a` and `c3.a` are not a valid constant expressions.

**Comment by iarkh** [comment]
> 2\. `co19_2/LanguageFeatures/Constant-update-2018/NewOperators_A01_t06/none` has an error because `MyClass(d1, -14)` evaluates `14 >>> -14`, and shifts are defined only for non-negative RHS.

I was unable to find any mention in the Spec that triple shift is allowed for non-negative arguments only. So should I file a bug against the Spec?

BTW - is zero triple shift allowed or not?

**Comment by eernstg** [comment]
It would not be consistent for the spec to indicate that a given operator has a specific semantics, or even specific typing properties.

This point is a little bit subtle. For instance, the spec mentions that `e1 == e2` has type `bool` and returns false if the first operand is non-null and the second one is null, but that's because the evaluation of an _equality expression_ is not the same thing as an invocation of the `operator ==` instance method. The equality expression evaluation treats the null object as an exception. Similarly, there is a special treatment of `e1 + e2` during type checks when the operands both have type `int` or both have type `double`. But these things are exceptions, that is, properties which would not hold if we were to rely completely on the standard rules for instance method typing and behavior. The spec never specifies any particular treatment or properties of the operators themselves, they are just instance methods.

This means that it is an issue for the dartdoc comments on core library classes like `int` to say whether or not it is an error to use a negative operand on the right hand side of `>>>`, and also that such comments would not be applicable for any other implementation than that of `int`.

With respect to testing, we should probably take this in two steps. We can test the syntax separately using a declaration of `operator >>>(...)` in a user-written class. The tests regarding the semantics of `>>>` on integers could be written now as well, but we know that it isn't implemented yet so we will just have to use the standard procedure for that (for co19 tests I'm not sure whether this means status files or preapprovals, but it should just be done in the usual manner).

**Comment by leafpetersen** [comment]
@lrhn @eernstg I think there was some confusion about how to interpret the response from @eernstg above.  The integer_t04.dart test landed [here](https://github.com/dart-lang/co19/commit/a0a24a4bd5e4d913264fccfd600139af5b20c8e9) is incorrectly checking that it is a static error for the RHS to be a negative integer.  

I believe there is an intended runtime error, but I'm not sure.  cc @srawlins @scheglov @johnniwinther

**Comment by lrhn** [comment]
It's a runtime error. The `int.>>>` operator has `int` as operand type, so the only static error we can give is if the operand is not an `int` (or if it's a `const` expression and it would throw at runtime, like it does for negative shift values).
We have no special affordances for that particular operator in the spec, other than to say that it can be constant.

**Comment by eernstg** [comment]
PS: It has been fixed, https://github.com/dart-lang/co19/blob/master/Language/Expressions/Shift/integer_t04.dart now expects run-time errors. So it should be OK after the next co19 roll.

**Comment by sgrekhov** [comment]
Closing this issue as fixed
