### ISSUE TITLE
LibTest/io/Directory/watch_A02_t01.dart mismatched asyncStart in timeout

### ISSUE THREAD

**Issue by sortie** [dart-lang/co19#372]
The test `LibTest/io/Directory/watch_A02_t01.dart` doesn't seem to work because the event never seems to occur. However, the test is failing because the `asyncStart()` isn't balanced in the onTimeout case. No exception is thrown, meaning the test fails with Fail instead of RuntimeError. Is that intended?

**Comment by sgrekhov** [comment]
@sortie tests works well for me on Windows (Dart VM version: 2.3.2-dev.0.0 (Tue May 21 22:23:41 2019 +0200) on "windows_x64")

Test does the following. First, it creates the following directory structure
- sandbox
  - dir <- watch this directory by `dir.watch(events: FileSystemEvent.create,  recursive: true)`
    - child

Then, it calls `child.createTempSync();` which creates a temp subdirectory in `child` directory. Because `resursive` is `true` in `dir.watch()` call, the tests expects that this create event must be watched. And this is true on Windows.

Added Expect.fail() on timeout

**Comment by sortie** [comment]
Thanks @sgrekhov. It doesn't seem to work on Linux for me, I'll look into that part. My worry was that it didn't seem to fail properly, which you've now fixed. So this seems closed to me.
