### ISSUE TITLE
Shadow DOM events that are always stopped tests out of date

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#52]
I'm seeing a failure in co19/WebPlatformTest/shadow-dom/events/events-that-are-always-stopped/test-006_t01 in Chrome which seems to be due to changes in the browser, not to any problem of ours. The current spec says that the scoped attribute should default to true, rather than the events always being stopped, but we don't have a scoped attribute visible yet. I see it landing in Chrome in Januaryin https://codereview.chromium.org/1586563005/ but it seems like it will only be set that way when the UA creates the event directly. I'm not sure what's best to be done, but for the moment I'm suppressing the test failure.

**Comment by sgrekhov** [comment]
Chrome behaviour changed, JS analog of this test produce the same result. Event doesn't stop at shadow boundary (even with scoped flag set to true) in Chrome 54. But it works in Chrome 45. So we should either change an expected result of the tests or delete them at all because Shadow DOM specification does not contain statement that is tested by these tests

**Comment by sgrekhov** [comment]
Fixed by fix for #107
