### ISSUE TITLE
Errors co19/LanguageFeatures/nnbd/future_flattening_A01_* tests

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/co19#785]
The tests
```
co19/LanguageFeatures/nnbd/future_flattening_A01_t12 Fail (expected Pass)
co19/LanguageFeatures/nnbd/future_flattening_A01_t40 Fail (expected Pass)
```
expect an error to be thrown at runtime when returning `null` through an async function. This as not the case for weak mode.

**Comment by eernstg** [comment]
Took a look at these tests, noted a couple of confusing statements in the top comment:

> Check that type of [await] expression matches with expected
> non-nullable legacy types dynamically and the expression cannot be [null].
> Check that compile error is not thrown if <A> is a legacy class, synchronous
> function with [Future<A>] return value type returns a value of the type
> [dynamic].

These tests are executed with unsound null-safety (`Requirements=nnbd-weak`), and this means that the dynamic type check (`arg as A`) will succeed, and we _will_ reach `Expect.fail("Should not reach here!")`.

Also when `A` is a type that occurs in an opted-in library it is a non-nullable type, both in the case where it denotes a class that is declared in a legacy library, and when it denotes a class declared in an opted-in library.

So there should not be a compile-time error at the point where an expression of type `dynamic` is returned in an `async` function with declared return type `Future<A>`, but that's because `dynamic` is assignable to the future value type of `test` (that is: `A`), and the question is the same both when `A` is declared in an opted-in library and when it's declared in a legacy library.
