### ISSUE TITLE
co19_2/ new failing tests

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#805]
With https://dart-review.googlesource.com/c/sdk/+/153742, new co19_2 tests are failing, because analyzer makes some diagnostics warnings instead of errors. The language specification says that they are warnings.

So, following tests are fixed:
```
co19/Language/Classes/Instance_Methods/Operators/return_type_t01
co19/Language/Classes/Setters/return_type_not_void_t01
co19/Language/Classes/Setters/syntax_t04
co19/Language/Classes/Setters/syntax_t05
co19/Language/Libraries_and_Scripts/Imports/library_name_t01
```

And the following tests are broken:
```
co19_2/Language/Classes/Instance_Methods/Operators/return_type_t01
co19_2/Language/Classes/Setters/return_type_not_void_t01
co19_2/Language/Classes/Setters/same_name_getter_different_type_t01
co19_2/Language/Classes/Setters/syntax_t04
co19_2/Language/Classes/Setters/syntax_t05
co19_2/Language/Libraries_and_Scripts/Imports/library_name_t01
```

I don't know if we want to spend time updating `co19_2/` tests, but want to document why I'm accepting breakages of these tests on bots. @eernstg

**Comment by sgrekhov** [comment]
@scheglov CL, mentioned in this issue was abandonded. Is this issue still actual then?

**Comment by eernstg** [comment]
Looking at the co19 repo (branch pre-nnbd) I don't see any missing updates in the co19_2 tests:

- co19_2/Language/Classes/Instance_Methods/Operators/return_type_t01 is an error, expects an error: OK.
- co19_2/Language/Classes/Setters/return_type_not_void_t01 is an error, expects an error: OK.
- co19_2/Language/Classes/Setters/same_name_getter_different_type_t01 is an error, expects an error: OK.
- co19_2/Language/Classes/Setters/syntax_t04 is an error, expects an error: OK (don't know why it's called 'syntax').
- co19_2/Language/Classes/Setters/syntax_t05 is an error, expects an error: OK (don't know why it's called 'syntax').
- co19_2/Language/Libraries_and_Scripts/Imports/library_name_t01 no errors, expects no errors: OK.

But the co19 tests (branch master) except the library name test still expect warnings, so they should be updated to expect errors:

- co19/Language/Classes/Instance_Methods/Operators/return_type_t01 is error, expects warning: Update.
- co19/Language/Classes/Setters/return_type_not_void_t01 is error, expects warning: Update.
- co19/Language/Classes/Setters/syntax_t04 is error, expects warning: Update.
- co19/Language/Classes/Setters/syntax_t05 is error, expects warning: Update.
- co19/Language/Libraries_and_Scripts/Imports/library_name_t01 no errors, expects no errors: OK.

So, presumably, the co19 tests have already been updated to expect warnings, but they should now be changed back because we changed the spec to require errors (which means that the analyzer already did the right thing).

**Comment by scheglov** [comment]
I think we also need to change these tests from warnings to compile-time errors:
```
co19/Language/Classes/Setters/same_name_getter_different_type_t01
co19/Language/Classes/Setters/same_name_getter_different_type_t02
```

**Comment by sgrekhov** [comment]
@eernstg after the change tests 
co19/Language/Classes/Instance_Methods/Operators/return_type_t01
co19/Language/Classes/Setters/return_type_not_void_t01
co19/Language/Classes/Setters/syntax_t04
co19/Language/Classes/Setters/syntax_t05
started failing on CFE with MissedCompileError. Do we have a corresponding issue for CFE? I was unable to find it.

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/issues/1012#issuecomment-662917122, I think it's #42701, #42702.

**Comment by sgrekhov** [comment]
Thank you.
