### ISSUE TITLE
Errors in the migrated Language/Generics/typedef_A04_t03.dart 

### ISSUE THREAD

**Issue by nshahan** [dart-lang/co19#823]
In weak mode I believe the last two expectations are not valid since the subtype relation is weakened to allow that the return type `X` is a subtype of `X?`.  I think this tests need to be broken into a sound and weak version so the expectations can differ in the two modes.

https://github.com/dart-lang/co19/blob/4cf836feb9b94579e9b399c74734f574ef7e8415/Language/Generics/typedef_A04_t03.dart#L38-L39

@eernstg Please double check my understanding here.

**Comment by eernstg** [comment]
Right, the weak mode dynamic type checks will erase the `?` also when it occurs inside a function type, so those two `is` checks should evaluate to true in weak mode. It should be possible to use `isWeakMode` to avoid splitting the test.

**Comment by sgrekhov** [comment]
@eernstg please review 93e98ef. Is `null is Never` a reliable way of weak mode detecting?

**Comment by eernstg** [comment]
The test in pkg/expect/lib/expect.dart is `bool get isWeakMode => const <Null>[] is List<Object>;` which is relying on the fact that `Null* <: Object*`, and I think that's a good choice.

The treatment of null is [special](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#runtime-checks-and-weak-checking). For `null is Never` we get true in any mode when it occurs in a legacy library and false in any mode when it occurs in an opted-in library, so that's not safe.
