### ISSUE TITLE
Analyzer warnings in new property extraction tests

### ISSUE THREAD

**Issue by whesse** [dart-lang/co19#88]
Five new property extraction tests give static warnings in the analyzer, and have been marked in the dart2js-analyzer.status file:

Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/no_
     such_method_t01: StaticWarning # Please triage this failure.
  79 Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/pro
     xy_annotation_t05: StaticWarning # Please triage this failure.
  80 Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/pro
     xy_annotation_t06: StaticWarning # Please triage this failure.
  81 Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/pro
     xy_annotation_t07: StaticWarning # Please triage this failure.
  82 Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/pro
     xy_annotation_t08: StaticWarning # Please triage this failure.

**Comment by sgrekhov** [comment]
For Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/no_
such_method_t01 static warning is an expected behaviour. @static-warning annotation added.

As for proxy_annotation_t05 ... proxy_annotation_08 test, they are failing because of https://github.com/dart-lang/sdk/issues/15467

@whesse, please add to the proxy_annotation_t05 ... proxy_annotation_08 strings in the status file comment # Issue 15467 
Also please remove the string Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/no_
such_method_t01: StaticWarning # Please triage this failure.
