### ISSUE TITLE
Some tests for instantiate-to-bound and super-bounded should be updated

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#984]
I'm [working](https://dart-review.googlesource.com/c/sdk/+/180020) on an update to checking regular-bounded and super-bounded types, motivated by [this change](https://github.com/dart-lang/language/pull/1133/files). I see failures in `co19` and `co19_2` tests. See details in the [test results](https://dart-ci.firebaseapp.com/cl/180020/1).

/cc @eernstg

**Comment by sgrekhov** [comment]
@scheglov how changes related with NNBD may affect co19_2 tests? These tests are pre-nnbd ones

**Comment by eernstg** [comment]
I agree that dart-lang/language#1133 is intended to change instantiation to bound and super-bounded types only for code with null safety.

Each of the helper predicates **TOP**, **NULL**, **MORETOP**, **MOREBOTTOM** mention types availably only with null safety; **OBJECT** implies null safety because **OBJECT**(`dynamic`) is false, and **BOTTOM** is followed by a sentence that implies null safety: '**BOTTOM**(`T`) is true if and only if `T` is a subtype of `Never`' (**BOTTOM**(`Null`) is false, but in Dart before null safety we had `Null <: T` for all `T`).

So moving the helper predicates to the null safety spec should not imply that they now mean something different, and hence 'resources/type-system/upper-lower-bounds.md' should also not mean something different than it did before the change.

**Comment by eernstg** [comment]
Note that we will now treat top types in positions that have no variance and in invariant positions the same as top types in covariant positions, but this is not the same thing as saying that every type variable which is unused/invariant is now considered covariant:

```dart
typedef F<X> = void Function(); // X is unused.
typedef G<Y> = Y Function(Y); // Y is invariant.

void main() {
  F<dynamic> x1; // Here, `dynamic` occurs in a position with no variance.
  F<void Function(dynamic)> x2; // `dynamic` position: no variance.
  G<dynamic> x3; // `dynamic` position: invariant.
  G<void Function(dynamic)> x4; // `dynamic` position: invariant.
  G<List<dynamic>> x5; // `dynamic` position: invariant.
  F<G<dynamic>> x5; // `dynamic` position: invariant.
  G<F<dynamic>> x6; // `dynamic` position: no variance.
}
```

For the purpose of checking a super-bounded type there is no need to make a distinction between a position that is invariant and a position that has no variance: Let 'unrelated' mean 'either invariant or without variance', then any subterm of a term whose position is unrelated will again be unrelated. In particular, the position does not switch to a different variance when we go from a function type _F_ to to a parameter type of _F_, which is otherwise a situation where the variance changes (from covariant to contravariant, or from contravariant to covariant).
